apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bookinfo-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-cert # name from cluster-issuer
    traefik.ingress.kubernetes.io/router.middlewares: default-redirect@kubernetescrd
spec:
  rules:
  - host: william.techbash.otherdevopsgene.dev # replace william with your username
    # or william.techbash.otherdevopsgene.work or william.techbash.otherdevopsgene.xyz
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: productpage
            port:
              number: 9080
  tls:
  - hosts:
    - william.techbash.otherdevopsgene.dev # match the host above
    secretName: acme-tls-cert
