apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ratings
  name: ratings
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ratings
  template:
    metadata:
      labels:
        app: ratings
    spec:
      containers:
      - image: wrongratings
        name: wrongratings
