apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ratings
  name: ratings
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ratings
  template:
    metadata:
      labels:
        app: ratings
    spec:
      containers:
      - image: docker.io/istio/examples-bookinfo-ratings-v1:1.20.2
        name: examples-bookinfo-ratings-v1
