apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: reviews
  name: reviews
  namespace: default
spec:
  replicas: 4
  selector:
    matchLabels:
      app: reviews
  template:
    metadata:
      labels:
        app: reviews
    spec:
      containers:
      - image: docker.io/istio/examples-bookinfo-reviews-v2:1.20.2
        name: examples-bookinfo-reviews-v2
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /health
            port: 9080
        readinessProbe:
          httpGet:
            path: /health
            port: 9080
